import Provider from './context/AuthContext'
import NavBar from './components/NavBar'
import Footer from './components/Footer'
import ToasterContext from './context/TosterContext'
import { Helmet } from 'react-helmet';

export const metadata = {
  title: 'Mvptrade',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Helmet>
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-LKVLK12SJL"></script>
      <script>{`
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments)}
        gtag('js', new Date());

        gtag('config', 'G-LKVLK12SJL');
      `}
      </script>
      </Helmet>
      <body>
        <Provider>
          <ToasterContext/>
        <div className="main">
          <div className="gradient" />
        </div>

        <main className="app">
          <NavBar/>
          {children}
          <Footer/>
        </main>
        </Provider>
      </body>
    </html>
  )
}
